Jog 126 homepage refectoring
DHBW-Coding/jogdog pull request #23
Opened 2023-03-01 00:38 UTC by JGlumanda

refactored Home page

2023-03-04 17:31 UTC, GoGoWe requested changes
There are still small things to refector and the newest version of dev should be pulled in

2023-03-04 17:31 UTC, GoGoWe commented on lib/main.dart
> -    // Permission.storage,
This still hast to be implemebted
I will do that

2023-03-05 11:47 UTC, GoGoWe requested changes
Looks Nice
Nur die Stunde die Angezeigt wird passt nicht und das mit dem Hund müssen wir noch klären
Er sieht bei mir auch nicht so nice aus weil der Ausschnitt für die Transparantez schelcht ist

2023-03-05 11:47 UTC, GoGoWe commented on lib/pages/page_home.dart
> +              DateFormat('HH:mm:ss')
Es wird beim Starten der App immer angezeigt dann eine Stunde vergangen ist
Ich habs versucht auf die schnelle zu fixen aber am Format liegt es nicht und die "1 Stunde" wird angezeigt auf wenn _getSessionInfoOngoing() noch nicht aufgerufen wurde.

2023-03-05 17:50 UTC, JGlumanda commented on lib/pages/page_home.dart
> +              DateFormat('HH:mm:ss')
Kann ich leider nicht nachvollziehen und sollte Codewise auch nicht passieren

2023-03-05 21:07 UTC, GoGoWe approved these changes
Sieht gut aus find die Lösung auch nett 
Ich glaube die Standard Musik wird nicht abgespielt wenn man nicht auswählt und es ist auch nicht ganz klar dass es die überhaupt gibt da muss man maybe echt noch mit Finn sprechen

2023-03-06 15:08 UTC, nikho2000 approved these changes
Sieht sehr gut aus

2023-03-06 15:13 UTC, merged